### ISSUE TITLE
Write to a temporary directory rather than the user's home directory

### ISSUE THREAD

**Issue by jwokaty** [calabrialab/ISAnalytics#1]
I run the builds for Bioconductor and noticed that ISAnalytics is writing `ISAnalytics_reports` to the user's home directory, which isn't allowed (see [BioC Packages: Other Data](http://contributions.bioconductor.org/data.html#other-data). ISAnalytics writes to the user home directory on both release and devel. We recommend writing to a temporary directory instead using [BiocFileCache](https://github.com/Bioconductor/BiocFileCache) or the default R caching directory `tools::R_user_dir("ISAnalytics, which="cache")`. We appreciate your attention to this matter as well as your contribution to Bioconductor. Let me know if you have any questions.

**Comment by GiuliaPais** [comment]
Sorry, it is probably one of the examples that wasn't run with the appropriate option settings, could we have more info on which files are written so we can locate the problem and fix it? Thank you

**Comment by jwokaty** [comment]
For example, I see the following in our build user's home directory on the Linux builder:

```
biocbuild@nebbiolo1:~$ tree ISAnalytics_reports/
ISAnalytics_reports/
├── 2022-04-21_outlier_test_pool_fragments_report.html
├── 2022-04-22_outlier_test_pool_fragments_report.html
├── 2022-04-24_outlier_test_pool_fragments_report.html
├── 2022-04-25_outlier_test_pool_fragments_report.html
├── 2022-04-26_outlier_test_pool_fragments_report.html
├── 2022-04-27_outlier_test_pool_fragments_report.html
├── 2022-04-28_outlier_test_pool_fragments_report.html
├── 2022-04-29_outlier_test_pool_fragments_report.html
├── 2022-05-01_outlier_test_pool_fragments_report.html
└── 2022-05-02_outlier_test_pool_fragments_report.html
```

Thanks for looking into this.

**Comment by GiuliaPais** [comment]
> For example, I see the following in our build user's home directory on the Linux builder:
> 
> ```
> biocbuild@nebbiolo1:~$ tree ISAnalytics_reports/
> ISAnalytics_reports/
> ├── 2022-04-21_outlier_test_pool_fragments_report.html
> ├── 2022-04-22_outlier_test_pool_fragments_report.html
> ├── 2022-04-24_outlier_test_pool_fragments_report.html
> ├── 2022-04-25_outlier_test_pool_fragments_report.html
> ├── 2022-04-26_outlier_test_pool_fragments_report.html
> ├── 2022-04-27_outlier_test_pool_fragments_report.html
> ├── 2022-04-28_outlier_test_pool_fragments_report.html
> ├── 2022-04-29_outlier_test_pool_fragments_report.html
> ├── 2022-05-01_outlier_test_pool_fragments_report.html
> └── 2022-05-02_outlier_test_pool_fragments_report.html
> ```
> 
> Thanks for looking into this.

Perfect, thank you, it will be fixed likely by tomorrow

**Comment by GiuliaPais** [comment]
We just pushed the fix on both release and devel, please let us know if the problem persists, have a nice day
